### ISSUE TITLE
Dragons in Python

### ISSUE THREAD

**Issue by szabolcsdombi** [kosua20/herebedragons#11]
Hello!

I was wondering if there are dragons in python too.
I found none, so I had to add them.

[herebedragons-python](https://github.com/cprogrammer1994/herebedragons-python)

**Comment by kosua20** [comment]
Ahahah, that's awesome. Thanks a lot! I've added a 'Other implementations' section to the main README so I could link to your repo and credit you.

**Comment by szabolcsdombi** [comment]
Thank you!
