### ISSUE TITLE
Scene does not include Utah Teapot

### ISSUE THREAD

**Issue by jherico** [kosua20/herebedragons#14]

**Comment by kosua20** [comment]
Alas, I had to pick some models at the beginning of this project and I've always preferred dragons to teapots (no offense...).

Some kind of 3D gallery with all the important/historical models and textures in computer graphics, along with the history of each one would be something interesting I guess!

**Comment by jherico** [comment]
> along with the history of each one would be something interesting I guess

Actually, this suggests a compelling feature....  rendering of HTML content.  If each scene could include the wikipedia entry on the model that would be an good marker for the presence or absence of an important feature in the underlying platform.
