### ISSUE TITLE
Metal won't work with Xcode 9

### ISSUE THREAD

**Issue by pengliu916** [kosua20/herebedragons#15]
May need to update to adopt Xcode 9

**Comment by kosua20** [comment]
The project seems to run fine using Xcode 9 Beta 4 on Sierra (10.12.6) and Swift 3.
I've converted it to Swift 4 but will wait at least for the GM release of Xcode 9 before pushing it.
Did you encounter any specific bug apart from the automatic conversion to Swift 4, maybe on High Sierra?

**Comment by pengliu916** [comment]
I tried compile on Sierra and Swift 3.2/4 both failed (swift 3.2 complain the ModelIO:<unknown>:0: error: fatal error encountered while reading from module 'ModelIO') I will update my macOS, Xcode version and try again, any suggestions?

**Comment by kosua20** [comment]
I've converted the Metal version to Swift 4 and tested it in Xcode 9, so normally everything should work now. If you have the time, tell me if everything is working on your side! Thanks!

**Comment by kosua20** [comment]
I've haven't encountered the issue on any machine on my side, closing this for now.
