### ISSUE TITLE
Add DirectX Toolkit version

### ISSUE THREAD

**Issue by speps** [kosua20/herebedragons#6]
I'm adding this as an issue mostly because I want to do it but I can't commit any time to it yet or rather can't predict when I'll find some time to do it.

However, it should be a good exercise for anyone.

DirectXTK: https://github.com/Microsoft/DirectXTK

**Comment by kosua20** [comment]
Thank your for this suggestion! If you find the time for this project, I'll gladly accept a PR. I've added a few details in the CONTRIBUTING.md file, maybe other people will be interested and could help with this version.

**Comment by kosua20** [comment]
Versions for DX9, DX11 and DX12 have been added recently, closing this 😃
