### ISSUE TITLE
Glide API test

### ISSUE THREAD

**Issue by artur** [kosua20/herebedragons#7]
If you can get your hands on a 3DFX Voodoo card it would be awesome to test it on Glide!

**Comment by jamsiedaly** [comment]
Glide was added to DOSBox a few years back so it may be possible to emulate this.

http://www.si-gamer.net/gulikoza/glide.html

**Comment by kosua20** [comment]
I wasn't aware of this specific API (I'm too young I guess :-) ), but this would be really fun ; I might look into it!

**Comment by kosua20** [comment]
A Glide version has been added (only compiled for the Voodoo 1 and tested in DosBox-X) 😃
