### ISSUE TITLE
Godot Engine Version

### ISSUE THREAD

**Issue by philiplb** [kosua20/herebedragons#8]
Hi,
a version for the [Godot Engine 3.0](http://godotengine.org/) would be nice as soon as at least a beta is released. :)
I might do a pull request then.

**Comment by kosua20** [comment]
That would be nice to see the scene ported to Godot!
I've added a few details in CONTRIBUTING.md concerning additional versions and pull requests, nothing too specific, this is simply to ensure that all new versions follow the same layout (a README with some screenshots, mainly).
Thank you for this proposition!

**Comment by kosua20** [comment]
Godot 4 version has been added recently, closing this 😃

**Comment by philiplb** [comment]
Now that's a glimpse from the past.
Awesome!
