### ISSUE TITLE
Info: the PS2 demo runs on real hardware

### ISSUE THREAD

**Issue by UwUnyaa** [kosua20/herebedragons#9]
I've tried launching the PS2 version of this demo using uLaunchELF on my PAL PS2 slim, and it seems to work without any issues.

It might be worth adding that the PS2 demo was tested on real hardware as well. I can provide photos of it running as well if there's interest.

**Comment by kosua20** [comment]
That's awesome! I could only test it in PCSX2 so I was worried that it wouldn't run at all on real hardware. I would be extremely interested into getting some photos. I am also curious about the performances: does it run smoothly?

Thank you!

**Comment by UwUnyaa** [comment]
It seems to run just fine. I'll upload photos later.

**Comment by UwUnyaa** [comment]
Here's the gallery of a couple photos I took: http://imgur.com/a/gsXXr

**Comment by kosua20** [comment]
Thank you for testing and taking the photos, I will add these pictures to the readme and credit you!
